### ISSUE TITLE
关于使用说明

### ISSUE THREAD

**Issue by rayblade** [reycn/ProxyRSS#1]
你好，请问使用说明能否在清楚一点呢？有很多地方没看懂。比如socks5_proxy是否是用于FQ更新SSR 订阅地址的？temp_proxy是否支持SSR？ssr_uri_list是什么没搞明白。我使用Python 3.6.9测试了一下，python3.6 main.py提示成功，但没有更新代理订阅地址。python3.6 server.py无任何输出。python3.6 uri.py提示requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.。使用的系统是debian9。

**Comment by reycn** [comment]
您好，这个我正在开发，目前网上的版本没法用简单的方式正常使用，所以也暂时没有文档。
最近在写论文，可能要过一阵子才能用。
一旦成熟会撰写详细文档，望保持关注。
